name: GitHub Build
run-name: Build a release version of Distributed Animate Dead 🪦💀.
on:
  push:
    branches:
      - master
      - 'releases/**'
    tags:
      - 'v**'
jobs:
  Build-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Access For SubModules
        uses: shaunco/ssh-agent@git-repo-mapping
        with:
          ssh-private-key: |
            ${{ secrets.SSH_ANIMATEDEAD }}
            ${{ secrets.SSH_MALMAX }}
            ${{ secrets.SSH_APACHELOGS }}
            ${{ secrets.SSH_COVERAGELOGS }}
          repo-mappings: |
            github.com/silverfoxy/AnimateDead
            github.com/silverfoxy/malmax
            github.com/silverfoxy/animate_dead_logs
            github.com/silverfoxy/animate_dead_coverage_logs
      - name: Checkout The Repositories
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependencies
        uses: php-actions/composer@v6
      - run: ./install-deps.sh