name: GitHub Build
run-name: Build a release version of Distributed Animate Dead 🪦💀.
on:
  push:
    branches:
      - master
      - 'releases/**'
    tags:
      - 'v**'
jobs:
  Build-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Access For SubModules
        uses: shaunco/ssh-agent@git-repo-mapping
        with:
          ssh-private-key: |
            ${{ secrets.SSH_ANIMATEDEAD }}
            ${{ secrets.SSH_MALMAX }}
            ${{ secrets.SSH_APACHELOGS }}
            ${{ secrets.SSH_COVERAGELOGS }}
          repo-mappings: |
            github.com/silverfoxy/AnimateDead
            github.com/silverfoxy/malmax
            github.com/silverfoxy/animate_dead_logs
            github.com/silverfoxy/animate_dead_coverage_logs
      - name: Checkout The Repositories
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependencies For Distributed AnimateDead
        uses: php-actions/composer@v6
        working-directory: ./app/php/client
      - name: Install Dependencies For AnimateDead
        uses: php-actions/composer@v6
        working-directory: ./app/php/client/animate_dead
      - name: Install Dependencies For MalMax
        uses: php-actions/composer@v6
        working-directory: ./app/php/client/animate_dead/vendor/silverfoxy/malmax
      - name: Install Dependencies For PHP-Emul
        uses: php-actions/composer@v6
        working-directory: ./app/php/client/animate_dead/vendor/silverfoxy/malmax/php-emul
      - name: Copy Default Config
        working-directory: ./app/php/client/animate_dead/
        run:  cp config.sample.json config.json